### ISSUE TITLE
Incorrect Path to `package.json` on Windows 11 Due to Extra Drive Letter

### ISSUE THREAD

**Issue by Victor-Kariuki** [kerwanp/adonis-cockpit#16]
#### Problem:
I am encountering an issue when configuring the package `adonis-cockpit` on Windows 11. The path to `package.json` is incorrectly assigned by adding an extra drive letter in the path, resulting in the following error:

RuntimeException: Unable to configure package "adonis-cockpit"
Error: Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\C:'

This error occurs when attempting to load `package.json` in the `./configure.ts` file using the following code:

```typescript
PATH: ./configure.ts
await PackageJson.load(command.app.appRoot.pathname)
```

On Windows 11, it seems that the path is being set with an extra drive letter (C:\C:\), which is causing the error.

Steps to Reproduce:
Use Windows 11.
Attempt to configure adonis-cockpit.
Notice that the incorrect path (C:\C:\) is assigned to package.json.
Expected Behavior:
The correct path to package.json should be assigned without duplicating the drive letter, like C:\path\to\project\package.json.

Environment:
OS: Windows 11
Package: adonis-cockpit
Node.js Version: v20.17.0
AdonisJS Version: v6

**Comment by kerwanp** [comment]
Hey! This is something I'm trying to fix https://github.com/kerwanp/adonis-cockpit/pull/14 but without a Windows environment I can't really debug properly. If you want to give it a try to fix it, feel free!

**Comment by kerwanp** [comment]
Issue solved! You should now be able to properly configure Cockpit.
