### ISSUE TITLE
can this works with react

### ISSUE THREAD

**Issue by Fawwaz-2009** [kerwanp/adonis-cockpit#17]
Hi Martin 👋 , this looks great!, I tried to set it up in my adonisjs project that uses inertia with reactjs but got the below error. I know that you are using vuejs but I wanted to ask if this would still work in a project like mine, only it would work with projects using vuejs?

![image](https://github.com/user-attachments/assets/24fe5797-86f7-4286-aa29-2dc58e45ea7d)

**Comment by kerwanp** [comment]
Hi! Adonis Cockpit is built with Vue so you will need to install the Vue plugin in your vite.config.ts.

But no worries you can still use React for your Frontend as they are different Inertia apps.

**Comment by Fawwaz-2009** [comment]
thanks a bunch adding the pluging did indeed remove the error screen but now just seeing empty white screen which I guess it's not what i should be seeing, will try to debug if all fails will try to create reproduction in a new repo.

![image](https://github.com/user-attachments/assets/376f526b-874b-4a30-9431-133af197470a)
![image](https://github.com/user-attachments/assets/8e3ef2e9-dc8a-487a-b8bf-a2f435e17eb7)

**Comment by Fawwaz-2009** [comment]
Hey Martin, so I tried installing cockpit into a fresh react and adonis js project and got the same results. created this repo to help debug the issue.
https://github.com/Fawwaz-2009/cockpit-react-adonis

**Comment by kerwanp** [comment]
This is really strange, I'll try to investigate further. Thanks a lot for the reprod.
It seems that Vite does not want to optimize deps.

Can you try by adding this in your vite.config.ts:
```ts
export default defineConfig({
  optimizeDeps: {
    include: ['nprogress']
  }
})
```

If you have a similar error with an other package, try by adding it in the include (and reporting it here)

**Comment by kerwanp** [comment]
After some testings thanks to @Fawwaz-2009 reproduction I've been able to provide a proper fix. You must add the following in your `vite.config.ts`
```ts
export default defineConfig({
  optimizeDeps: {
    include: ['@inertiajs/vue3', 'vue']
  },
  // ...rest of your config
})
```

I will add it directly in the Cockpit plugin in a future version.

**Comment by Fawwaz-2009** [comment]
thanks a bunch Martin, that last fix worked perfectly the only remaining issue was that the tailwindcss for cockpit were not applying, after digging into it seems that I had to patch the `content` field in the tailwind configs and that fixed the issue 

```
import cockpit from "adonis-cockpit/tailwind";

/** @type {import('tailwindcss').Config} */
export default {
  presets: [cockpit],
  darkMode: ["class"],

  content: ["./resources/**/*.edge", "./resources/**/*.{js,ts,jsx,tsx,vue}", "./inertia/**/*.{js,ts,jsx,tsx,vue}", ...cockpit.content],

  // eslint-disable-next-line unicorn/prefer-module
  plugins: [require("tailwindcss-animate"), ...cockpit.plugins],
};
```
![image](https://github.com/user-attachments/assets/1d8bf56c-3eff-4b8e-87dc-75e967875db2)
